---
title: "hw1 p1"
output: pdf_document
---

```{r}
data = read.csv("pima-indians-diabetes.csv")
data
```

```{r}
#install.packages("dplyr")
library(dplyr)
sample1_train = sample_n(data, as.integer(nrow(data)*0.8))
sample1_test = anti_join(data, sample1_train)
```

```{r}
P_c1 = length(sample1_train$X1[sample1_train$X1 == 1])/nrow(sample1_train)
P_c1
P_c0 = 1 - P_c1
P_c0
```

```{r}
col_1_mean = sapply(sample1_train[sample1_train$X1 == 1,], mean)
col_0_mean = sapply(sample1_train[sample1_train$X1 == 0,], mean)
col_1_sd = sapply(sample1_train[sample1_train$X1 == 1,], sd)
col_0_sd = sapply(sample1_train[sample1_train$X1 == 0,], sd)
col_1_mean
col_0_mean
col_1_sd
col_0_sd
```

```{r}
sample1_test$X6_P1 = dnorm(sample1_test$X6, col_1_mean[1], col_1_sd[1], log = TRUE)
sample1_test$X6_P0 = dnorm(sample1_test$X6, col_0_mean[1], col_0_sd[1], log = TRUE)
sample1_test$X148_P1 = dnorm(sample1_test$X148, col_1_mean[2], col_1_sd[2], log = TRUE)
sample1_test$X148_P0 = dnorm(sample1_test$X148, col_0_mean[2], col_0_sd[2], log = TRUE)
sample1_test$X72_P1 = dnorm(sample1_test$X72, col_1_mean[3], col_1_sd[3], log = TRUE)
sample1_test$X72_P0 = dnorm(sample1_test$X72, col_0_mean[3], col_0_sd[3], log = TRUE)
sample1_test$X35_P1 = dnorm(sample1_test$X35, col_1_mean[4], col_1_sd[4], log = TRUE)
sample1_test$X35_P0 = dnorm(sample1_test$X35, col_0_mean[4], col_0_sd[4], log = TRUE)
sample1_test$X0_P1 = dnorm(sample1_test$X0, col_1_mean[5], col_1_sd[5], log = TRUE)
sample1_test$X0_P0 = dnorm(sample1_test$X0, col_0_mean[5], col_0_sd[5], log = TRUE)
sample1_test$X336_P1 = dnorm(sample1_test$X33.6, col_1_mean[6], col_1_sd[6], log = TRUE)
sample1_test$X336_P0 = dnorm(sample1_test$X33.6, col_0_mean[6], col_0_sd[6], log = TRUE)
sample1_test$X627_P1 = dnorm(sample1_test$X0.627, col_1_mean[7], col_1_sd[7], log = TRUE)
sample1_test$X627_P0 = dnorm(sample1_test$X0.627, col_0_mean[7], col_0_sd[7], log = TRUE)
sample1_test$X50_P1 = dnorm(sample1_test$X50, col_1_mean[8], col_1_sd[8], log = TRUE)
sample1_test$X50_P0 = dnorm(sample1_test$X50, col_0_mean[8], col_0_sd[8], log = TRUE)
sample1_test
```

```{r}
sample1_test$sum_p1 = sample1_test$X6_P1+sample1_test$X148_P1+sample1_test$X72_P1+sample1_test$X35_P1+sample1_test$X0_P1+sample1_test$X336_P1+sample1_test$X627_P1+sample1_test$X50_P1 + log(P_c1)
sample1_test$sum_p0 = sample1_test$X6_P0+sample1_test$X148_P0+sample1_test$X72_P0+sample1_test$X35_P0+sample1_test$X0_P0+sample1_test$X336_P0+sample1_test$X627_P0+sample1_test$X50_P0 + log(P_c0)
sample1_test$sum_p1 
sample1_test$sum_p0
sample1_test$result = (sample1_test$sum_p1 > sample1_test$sum_p0)
sample1_test$result
accuracy = nrow(sample1_test[sample1_test$result == sample1_test$X1,])/nrow(sample1_test)
accuracy
```

```{R}
sum( 0.7532468,0.6948052,0.7467532,0.7987013,0.7597403,0.7207792,0.8311688,0.6948052,0.8376623, 0.7012987)/10
```




###PART B
```{r}
is.na(data[,3])<-!data$X72
is.na(data[,4])<-!data$X35
is.na(data[,6])<-!data$X33.6
is.na(data[,8])<-!data$X50
data
```

```{r}
sample2_train = sample_n(data, as.integer(nrow(data)*0.8))
sample2_test = anti_join(data, sample1_train)
P_c1 = length(sample1_train$X1[sample1_train$X1 == 1])/nrow(sample1_train)
P_c0 = 1 - P_c1

col_1_mean = sapply(na.omit(sample2_train[sample2_train$X1 == 1,]), mean)
col_0_mean = sapply(na.omit(sample2_train[sample2_train$X1 == 0,]), mean)
col_1_sd = sapply(na.omit(sample2_train[sample2_train$X1 == 1,]), sd)
col_0_sd = sapply(na.omit(sample2_train[sample2_train$X1 == 0,]), sd)

col_1_mean
col_0_mean
col_1_sd
col_0_sd

sample2_test$X6_P1 = dnorm(sample2_test$X6, col_1_mean[1], col_1_sd[1], log = TRUE)
sample2_test$X6_P0 = dnorm(sample2_test$X6, col_0_mean[1], col_0_sd[1], log = TRUE)
sample2_test$X148_P1 = dnorm(sample2_test$X148, col_1_mean[2], col_1_sd[2], log = TRUE)
sample2_test$X148_P0 = dnorm(sample2_test$X148, col_0_mean[2], col_0_sd[2], log = TRUE)
sample2_test$X72_P1 = dnorm(sample2_test$X72, col_1_mean[3], col_1_sd[3], log = TRUE)
sample2_test$X72_P0 = dnorm(sample2_test$X72, col_0_mean[3], col_0_sd[3], log = TRUE)
sample2_test$X35_P1 = dnorm(sample2_test$X35, col_1_mean[4], col_1_sd[4], log = TRUE)
sample2_test$X35_P0 = dnorm(sample2_test$X35, col_0_mean[4], col_0_sd[4], log = TRUE)
sample2_test$X0_P1 = dnorm(sample2_test$X0, col_1_mean[5], col_1_sd[5], log = TRUE)
sample2_test$X0_P0 = dnorm(sample2_test$X0, col_0_mean[5], col_0_sd[5], log = TRUE)
sample2_test$X336_P1 = dnorm(sample2_test$X33.6, col_1_mean[6], col_1_sd[6], log = TRUE)
sample2_test$X336_P0 = dnorm(sample2_test$X33.6, col_0_mean[6], col_0_sd[6], log = TRUE)
sample2_test$X627_P1 = dnorm(sample2_test$X0.627, col_1_mean[7], col_1_sd[7], log = TRUE)
sample2_test$X627_P0 = dnorm(sample2_test$X0.627, col_0_mean[7], col_0_sd[7], log = TRUE)
sample2_test$X50_P1 = dnorm(sample2_test$X50, col_1_mean[8], col_1_sd[8], log = TRUE)
sample2_test$X50_P0 = dnorm(sample2_test$X50, col_0_mean[8], col_0_sd[8], log = TRUE)

for(i in 1:nrow(sample2_test)){
  if(is.na(sample2_test$X6_P1[i])) sample2_test$X6_P1[i] = 0
  if(is.na(sample2_test$X6_P0[i])) sample2_test$X6_P0[i] = 0
  if(is.na(sample2_test$X148_P1[i])) sample2_test$X148_P1[i] = 0
  if(is.na(sample2_test$X148_P0[i])) sample2_test$X148_P0[i] = 0
  if(is.na(sample2_test$X72_P1[i])) sample2_test$X72_P1[i] = 0
  if(is.na(sample2_test$X72_P0[i])) sample2_test$X72_P0[i] = 0
  if(is.na(sample2_test$X35_P1[i])) sample2_test$X35_P1[i] = 0
  if(is.na(sample2_test$X35_P0[i])) sample2_test$X35_P0[i] = 0
  if(is.na(sample2_test$X0_P1[i])) sample2_test$X0_P1[i] = 0
  if(is.na(sample2_test$X0_P0[i])) sample2_test$X0_P0[i] = 0
  if(is.na(sample2_test$X336_P1[i])) sample2_test$X336_P1[i] = 0
  if(is.na(sample2_test$X336_P0[i])) sample2_test$X336_P0[i] = 0
  if(is.na(sample2_test$X627_P1[i])) sample2_test$X627_P1[i] = 0
  if(is.na(sample2_test$X627_P0[i])) sample2_test$X627_P0[i] = 0
  if(is.na(sample2_test$X50_P1[i])) sample2_test$X50_P1[i] = 0
  if(is.na(sample2_test$X50_P0[i])) sample2_test$X50_P0[i] = 0
}


sample2_test$sum_p1 = sample2_test$X6_P1+sample2_test$X148_P1+sample2_test$X72_P1+sample2_test$X35_P1+sample2_test$X0_P1+sample2_test$X336_P1+sample2_test$X627_P1+sample2_test$X50_P1 + log(P_c1)
sample2_test$sum_p0 = sample2_test$X6_P0+sample2_test$X148_P0+sample2_test$X72_P0+sample2_test$X35_P0+sample2_test$X0_P0+sample2_test$X336_P0+sample2_test$X627_P0+sample2_test$X50_P0 + log(P_c0)
sample2_test$sum_p1 
sample2_test$sum_p0
sample2_test$result = (sample2_test$sum_p1 > sample2_test$sum_p0)
sample2_test$result
accuracy = nrow(sample2_test[sample2_test$result == sample2_test$X1,])/nrow(sample2_test)
accuracy
```
```{R}
sum(0.7155425, 0.7071006, 0.7091988, 0.6918605, 0.7160121, 0.6920821, 0.7337662, 0.6978852, 0.6966967, 0.6929825) / 10
```

### Part D
```{R}
install.packages('klaR')
library('klaR')
library(e1071)
data = read.csv("pima-indians-diabetes.csv")
sample3_train = sample_n(data, as.integer(nrow(data)*0.8))
sample3_test = anti_join(data, sample3_train)
#model = svmlight(x = sample3_train[,1:8], grouping = sample3_train$X1)
1 - 144/nrow(sample3_train)
```
